version: '3.2'
services:
 relay:
   container_name: webhookrelay
   image: webhookrelay/webhookrelayd:latest
   network_mode: host # required if you want to access other services running on localhost (otherwise localhost would be inside this container)
   restart: always
   environment:
     # Authentication
     - RELAY_KEY=${RELAY_KEY}
     - RELAY_SECRET=${RELAY_SECRET}
     # buckets list to subscribe
     - BUCKETS=${BUCKETS}
     # Destination to filter on (if you have multiple outputs and only 
     # wish to forward one or more from the bucket)
     - DESTINATION=${DESTINATION}
